[build]
builder = "nixpacks"

[deploy]
startCommand = "bundle exec rails db:migrate && bundle exec rails server -b 0.0.0.0 -p $PORT"
healthcheckPath = "/users/sign_in"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
